---
title: 사용자 정의 예외 만들기, 예외 되던지기, 연결된 예외
categories:
  - Develop
tags:
  - Java
  - 자바의 정석 기초편
---
## 사용자 정의 예외 만들기

우리가 직접 예외 클래스를 정의할 수 있다.
조상은 Exception과 RuntimeException 중에서 선택한다.

```java
class MyException extends Exception {
  	MyException(String msg) { // 문자열을 매개변수로 받는 생성자
      	super(msg); // 조상인 Exception 클래스의 생성자를 호출한다. 
      	// 필수는 아니지만, 넣어주는 것이 보통이다.
    }
}
```

구체적으로 적으면 다음과 같다.

```java
class MyException extends Exception { 
 		// 에러 코드 값을 저장하기 위한 필드를 추가했다.
  	private final int ERR_CODE; // 생성자를 통해 초기화 (필요시 넣음)
  
  	MyException(String msg, int errCode) { // 생성자
      	super(msg); // 조상인 Exception 클래스의 생성자를 호출한다. 
      	// 필수는 아니지만, 넣어주는 것이 보통이다.
      	ERR_CODE = errCode;
    }
  	MyException(String msg) {
      	this(msg, 100); // ERR_CODE를 100(기본값)으로 초기화한다.
    }
  	public int getErrCode() { // 에러 코드를 얻을 수 있는 메서드도 추가했다.
      	return ERR_CODE; // 이 메서드는 주로 getMessage()와 함께 사용될 것이다.
    }
}
```
주요한 것은 Exception 혹은 RuntimeException을 조상으로 받는 것, 생성자 매개변수에 String을 넣는 것

## 예외 되던지기 (exception re-throwing)

예외를 처리한 후에 다시 예외를 발생시키는 것이다.
즉, 호출한 메서드와 호출된 메서드 양쪽 모두에서 예외처리하는 것이며, 예외를 두 번처리하는 것이다. 
(보통은 한 번 처리하지만, 특이하게 양쪽에서 처리하는 것이다.)
분담처리할 때 사용할 수 있다.

```java
public class Ex8_12 {
    public static void main(String[] args) {
        try  { // 예외 발생 다시 던지기
            method1();
        } catch (Exception e)	{
            System.out.println("main메서드에서 예외가 처리되었습니다.");
        }
    }	// main메서드의 끝

    static void method1() throws Exception {
        try { // 예외발생 던지기
            throw new Exception();
        } catch (Exception e) {
            System.out.println("method1메서드에서 예외가 처리되었습니다.");
            throw e; // 다시 예외를 발생시킨다. (원래 try-catch문으로 예외가 해결 되었기에 다시 발생시킴)
        }
    }	// method1메서드의 끝
}

// 결과
// method1메서드에서 예외가 처리되었습니다.
// main메서드에서 예외가 처리되었습니다.

```

## 연결된 예외(chained exception)

한 예외가 다른 예외를 발생시킬 수 있다.
예외 A가 예외 B를 발생시키면, A는 B의 원인 예외(cause exception)이다.

| Throwable initCause(Throwable cause) | 지정한 예외를 원인 예외로 등록 |
| ------------------------------------ | ------------------------------ |
| **Throwable getCause()**             | **원인 예외를 반환**           |

Throwable은 Exception과 Error의 조상이다.

![20220809_1](/assets/img/20220809_1.png)

```java
public class Throwable implements Serializable {
  	...
    private Throwable cause = this; // 객체 자신(this)을 원인 예외로 등록
  	...
    public synchronized Throwable initCause(Throwable cause) {
      ...
        this.cause = cause; // cause를 원인 예외로 등록
      	return this;
    }
		  ...
}
```

```java
void install() throws InstallException { // 실제 발생한 것은 SpaceException이지만, InstallException으로 쓴다.
  	try {
      	startInstall();
      	copyFiles();
    } catch (SpaceException e) { // 예외 A를 예외 B의 원인 예외로 등록함 (A = SpaceException)

      	InstallException ie = new InstallException("설치중 예외발생"); // 예외 생성
        ie.initCause(e); // InstallException의 원인 예외를 SpaceException으로 지정 (예외 B = InstallException)
      	throw ie; // InstallException을 발생시킨다.
      	// 두 예외를 연결된 예외라고 한다.
    } catch (MemoryException me){
      	...
    }
}
```

### 연결된 예외를 쓰는 이유

여러 예외를 하나로 묶어서 다루기 위해서 사용한다.

```java
try {
  	install();
} catch(SpaceException e) {
  	e.printStackTrace();
} catch(MemoryException e) {
  	e.printStackTrace();
} catch(Exception e) {
	  e.printStackTrace();
}
// 결과
// SpaceException : 설치할 공간이 부족합니다.
// at Ex_8_13.install(Ex.8_13.java:33)
// at Ex_8_13.main(Ex.8_13.java:16)
```

위의 catch {}을 아래와 같이줄일 수 있다.

```java
try {
  	install();
} catch(InstallException e) {
  	e.printStackTrace();
} catch(Exception e) {
  	e.printStackTrace();
}
```

installException을 만든 뒤에, 하게된다면 이전에 썼던 코드와 같다.

```java
void install() throws InstallException {
  	try {
      	startInstall();
      	copyFiles();
    } catch (SpaceException e) {
      	InstallException ie = new InstallException("설치중 예외발생");
        ie.initCause(e);
      	throw ie;
    } catch (MemoryException me){
      	...
    }
}

// 결과
// InstallException: 설치 중 예외발생 (대략적인 정보)
// at ch08.Ex8_13.install(Ex8_13.java:19)
// at ch08.Ex8_13.main(Ex8_13.java:6)
// Caused by: ch08.SpaceException2: 설치할 공간이 부족합니다. (세부정보)
// at Ex8_13.startInstall(Ex8_13.java:33)
// at Ex8_13.install(Ex8_13.java:16)

```

연결된 예외를 사용하게 되면, 대략적인 정보와 함께, 세부적인 정보까지 나온다.

또한, checked예외(필수처리 - Exception자손)를 unchecked예외(선택처리 - RuntimeException자손)로 변경하려할 때, 사용한다.

```java
static void startInstall() throws SpaceException2, MemoryException2 {
  																// 예외선언 (필수처리 = checked)를 선택처리로 바꾸고 싶을 때,
        if(!enoughSpace()) { 		// 충분한 설치 공간이 없으면...
            throw new SpaceException2("설치할 공간이 부족합니다.");
        }
```

RuntimeException을 하나 만들고, SpaceException을 그 안에 계속 넣는다.
Exception이 아닌 <u>RuntimeException이 발생한 것 처럼 위장한다.</u>

MemoryException을 필수에서 선택으로 바꿨다. (위의 코드와 비교)

```java
static void startInstall() throws SpaceException { // MemoryException는 아래, RuntimeException의 원인예외로 바뀐다.
		if (!enoughSpace()) // 충분한 공간이 없으면
      	throw new SpaceException("설치할 공간이 부족합니다.");
  
  	if (!enoughMemory()) // 충분한 메모리가 없으면
      	throw new RuntimeException(new MemoryException("메모리가 부족합니다."))
      	// 필수예외를 선택예외인 RuntimeException의 원인예외로 등록한다.
      	// checked를 unchecked로 변경한다.
} // startInstall메서드의 끝
```

세부적인 예외들을 포괄적인 예외들로 변경할 때, 사용하거나 checked예외를 unchecked예외로 변경할 때 사용한다.
